nelmio_api_doc:
    operation_id_generation: no_prepend
    documentation:
        servers:
            - url: '%env(DEFAULT_URI)%'
              description: 開発環境
        info:
            title: My Issue Tracker API
            version: 1.0.0
        components:
            securitySchemes:
                session:
                    type: apiKey
                    in: cookie
                    name: PHPSESSID
                    description: Session cookie obtained from login
        security:
            - session: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
