services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - ${LOCAL_IP}:${BACKEND_PORT}:80
    depends_on:
      database:
        condition: service_healthy
    command: ["./up.sh"]

  database:
    image: postgres:18.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d:ro
    ports:
      - ${LOCAL_IP}:${DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "${LOCAL_IP}:${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    command: ["./up.sh"]

volumes:
  database:
